	LDX	#0 		.X <- 0
LOOP	LDCH	ANSWER, X	.A = ANSWER[X]
	STA	STKF		.STKF = A = ANSWER[X]
	LDCH	GUESS, X		.A=GUESS[X]
	COMP	STKF		.STKF=A=GUESS[X]와 STKF=ANSWER[X] 비교
	JEQ	STRIKE		.만약 같은 값이면 STRIKE로 점프
	LDCH	GUESS,X 	.만약 현재 같은 값이 아니라면 현재 인덱스의 ANSWER[X]의 값 register A에 저장.
	JSUB	BALL1		.Register A에 ANSWER[X]의 값 저장 후 BALCHK로 JUMP해서 BALL의 유무 판단.
	J	OUTCHK		.BALL CHECK이후에 OUTCHK로 이동한다

STRIKE	LDA	#1
	ADD	STK		.STK 레지스터 값 1증가
	STA 	STK
	TIX	STRLEN
	JEQ	FIN
	JLT	LOOP

BALL1	STX	TEMP
	LDX	#0
	STA	DIFF
	J	BALL2

BALL2	LDCH	ANSWER,X
	COMP	DIFF
	JEQ	INCB
	TIX	STRLEN
	JEQ	OUTCHK
	JLT	BALL2
	
INCB	LDA	#1
	ADD	BALL
	STA	BALL
	LDX	TEMP
	TIX	STRLEN
	JEQ	FIN		.BALL 레지스터 값 1증가
	JLT	LOOP

OUTCHK	LDX	#0
	LDX	TEMP
	LDA	#1
	ADD	OUT
	STA	OUT		.OUT register value 		
	TIX	STRLEN
	JLT	LOOP
	JEQ	FIN	

FIN	TIX	STRLEN
		
TEMP	RESW	1
DIFF	RESW	1
STKF	RESW	1

STK	RESW	1
OUT	RESW	1
BALL	RESW	1

ANSWER	BYTE 	C'734'
GUESS	BYTE	C'678'

STRLEN	WORD	3